identify_institutions_task:
  description: >
    Identify potential institutions conducting active kinase drug discovery research in 2024,
    excluding a predefined list of institutions.

    CORE REQUIREMENTS:
    1. Only include institutions with verifiable 2024 research activities
    2. Focus on institutions with dedicated drug discovery infrastructure
    3. Ensure presence of quantitative assay capabilities
    4. Verify high-throughput screening facilities
    5. Confirm active kinase-specific research programs

  expected_output: >
    A list of institutions that potentially meet the core requirements, excluding those in the exclusion list.

collect_institution_data_task:
  description: >
    For each identified institution, collect the required data points:

    * Institution Name: Full official name
    * Research Division: Specific department/center name
    * Website: Primary research program URL
    * Research Focus: Primary kinase targets and therapeutic areas
    * Technical Capabilities:
        * Screening platforms
        * Assay technologies
        * Equipment specifications
    * 2024 Activities: Specific research initiatives or publications

    FORMAT TEMPLATE:
    Institution: [Full Official Name]
    Department: [Specific Research Unit]
    URL: [Research Program Website]
    Focus Areas: [Primary Kinase Targets]
    Technical Infrastructure: [Key Technologies]
    2024 Progress: [Current Activities]

  expected_output: >
    Detailed information for each institution, including the required data points, following the FORMAT TEMPLATE.

validate_and_filter_task:
  description: >
    Validate each institution against the following VALIDATION CRITERIA:

    1. Published kinase research in 2024
    2. Operating drug discovery facility
    3. Documented quantitative assay capabilities
    4. Active kinase-focused projects
    5. Verifiable screening infrastructure

    Apply the QUALITY FILTERS:

    * Exclude theoretical research only
    * Remove programs without wet lab facilities
    * Omit entries lacking 2024 documentation
    * Skip programs without kinase focus

  expected_output: >
    A refined list of institutions that meet all validation criteria, ready for prioritization.

prioritize_institutions_task:
  description: >
    Prioritize the final list of institutions based on:

    1. Research impact
    2. Technical capabilities
    3. Program scope
    4. Publication record
    5. Industry collaborations

    Present only verified information with supporting evidence from institutional sources.

  expected_output: >
    A prioritized list of verified institutions, formatted according to the specified template.

compile_results_task:
  description: >
    Compile and format the final list of institutions according to the FORMAT TEMPLATE,
    ensuring clarity and compliance with the requirements.

  expected_output: >
    A final compiled report of 50 institutions, formatted as per the prescribed template, ready for submission.
